# Общая функция для использования всех способов поиска

In [1]:
import import_ipynb
from preprocessing import *
from first_search import *
from dict_search import *
from matrix_search import *

Requirement already satisfied: pymorphy3 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (2.0.6)
Requirement already satisfied: dawg2-python>=0.8.0 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pymorphy3) (0.9.0)
Requirement already satisfied: pymorphy3-dicts-ru in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pymorphy3) (2.4.417150.4580142)
Requirement already satisfied: setuptools>=68.2.2 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pymorphy3) (80.9.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\obrid\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\obrid\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
100%|█████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:07<00:00, 265.75it/s]

Stored 'en_data' (DataFrame)
Requirement already satisfied: rank_bm25 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (0.2.2)
Requirement already satisfied: numpy in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from rank_bm25) (2.4.3)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\obrid\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

2000it [00:00, 14564.82it/s]
2000it [00:00, 16399.47it/s]
2000it [00:00, 12998.80it/s]
2000it [00:00, 15359.05it/s]
2000it [00:00, 20915.52it/s]
2000it [00:00, 14167.27it/s]
2000it [00:00, 4377.35it/s]

In [2]:
def general_search(query:str, index_type:str='bm', type_search:str='matrix', top_n:int=5, k=1.5, b=0.75):
    '''
    Принимает запрос, тип индекса (bm25/частотный), тип поиска (базовый, через словари или через матрицы), нужную длину топа документов. Возвращает топ документов по убыванию актуальности

    query:str -- запрос на русском языке
    
    index_type:str -- вид индекса:
        bm25 -- bm25
        frequency -- частотный
        
    type_search:str -- вид подсчета:
        basic -- базовый
        dictonary -- через словари
        matrix -- через матрицы
        
    top_n:int -- длина топа возвращаемых документов
    '''
    if index_type == 'bm':
        if type_search == 'basic':
            return search(query, top_k=top_n)
        elif type_search == 'dictionary':
            return dict_bm25(query, k, b, top_k=top_n) 
        elif  type_search == 'matrix':
            return matrix_bm(query, top_k=top_n, k=k, b=b)
        else:
            raise ValueError(f'Неверный type search -- {type_search}, доступные значения: basic, dictionary, matrix')
            
    elif index_type == 'frequency':
        if type_search == 'basic':
            return search(query, index_type='freq', top_k=top_n)
        elif type_search == 'dictionary':
            return dict_freq(query, top_k=top_n) 
            return matrix_freq(query, top_k=top_n)
        else:
            raise ValueError(f'Неверный type search -- {type_search}, доступные значения: basic, dictionary, matrix')
    else:
        raise ValueError(f'Неверный index type -- {index_type}, доступные значения: bm25, frequency')

ТУТ ПРОГОНИ ДЛЯ КАЖДОГО ВИДА: убедись, что работают и сходятся!

Примеры:

In [17]:
general_search('значения храма')

2000it [00:00, 14768.39it/s]

                                              target     bm_sim
0  Слово храм используется и в переносном значени...  11.703638
1  \nОсобое значение имеет символическое изображе...   8.774818
2  Слово храм имеет переносные значения. Храмом н...   6.559210
3  Каждый храм посвящён одному из христианских пр...   6.183873
4  Самыми большими православными храмами России я...   5.963079

In [18]:
general_search('Значения храма', type_search='basic')

2000it [00:00, 15881.92it/s]

                                              target     bm_sim
0  Слово храм используется и в переносном значени...  11.703638
1  \nОсобое значение имеет символическое изображе...   8.774818
2  Слово храм имеет переносные значения. Храмом н...   6.559210
3  Каждый храм посвящён одному из христианских пр...   6.183873
4  Самыми большими православными храмами России я...   5.963079

In [19]:
general_search('Значение храму!', type_search='dictionary', k=1.5)

                                              target     bm_sim
0  Слово храм используется и в переносном значени...  11.703638
1  \nОсобое значение имеет символическое изображе...   8.774818
2  Слово храм имеет переносные значения. Храмом н...   6.559210
3  Каждый храм посвящён одному из христианских пр...   6.183873
4  Самыми большими православными храмами России я...   5.963079

In [6]:
general_search('храм', index_type='frequency', type_search='dictionary')

2000it [00:00, 13014.09it/s]

                                                 text  храм
25  Слово храм имеет переносные значения. Храмом н...     5
22  Слово храм используется и в переносном значени...     3
31  Храм состоит из трех основных частей. Восточна...     3
37  Храм состоит из трех основных частей. Восточна...     3
50  Каждый храм посвящён одному из христианских пр...     3

In [8]:
general_search('весна у Тютчева', index_type='frequency', type_search='basic', top_n=10)

2000it [00:00, 16455.45it/s]

                                               texts  весна  тютчев  sum
0  Календарная весна продолжается три месяца: мар...    5.0     0.0  5.0
1  Стали крылатыми словами строки Ф. И. Тютчева: ...    3.0     1.0  4.0
2  В русском фольклоре существует выражение весна...    3.0     0.0  3.0
3  Многие стихотворения о весне положены на музык...    2.0     1.0  3.0
4  Слово весна имеет переносное значение: ‘пора р...    2.0     0.0  2.0
5  Государственный праздник. Нерабочий день. Офиц...    1.0     0.0  1.0
6  В 1240 г. крестоносцы Ливонского ордена захват...    1.0     0.0  1.0
7  \n8 Марта − первый весенний (см. весна) праздн...    1.0     0.0  1.0
8  \nВ русских сказках есть и другая Снегурочка –...    1.0     0.0  1.0
9  \nФольклорный образ лежит в основе пьесы-сказк...    1.0     0.0  1.0